/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CudaIndexJni */

#ifndef _Included_CudaIndexJni
#define _Included_CudaIndexJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CudaIndexJni
 * Method:    initIndex
 * Signature: ([I[F[I)I
 */
JNIEXPORT jint JNICALL Java_CudaIndexJni_initIndex
  (JNIEnv *, jobject, jintArray, jfloatArray, jintArray, jlong);

/*
 * Class:     CudaIndexJni
 * Method:    getScores
 * Signature: ([I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_CudaIndexJni_getScores
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
